Update 0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,16 @@
 #!/bin/bash
-print ("C is fun! ")
+
+# Check if $PYFILE is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: The environment variable \$PYFILE is not set."
+    exit 1
+fi
+
+# Check if the specified Python file exists
+if [ ! -f "$PYFILE" ]; then
+    echo "Error: The specified Python file '$PYFILE' does not exist."
+    exit 1
+fi
+
+# Run the Python script
+python "$PYFILE"
